/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  ggo --unamed-opts --no-handle-version --no-handle-error --file-name=cmd_useradd --func-name=useradd_cmdline_parser --arg-struct-name=useradd_args_info

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmd_useradd.h"

const char *useradd_args_info_purpose = "";

const char *useradd_args_info_usage = "Usage: sxacl useradd [OPTIONS] <username> sx://[profile@]cluster";

const char *useradd_args_info_versiontext = "";

const char *useradd_args_info_description = "";

const char *useradd_args_info_full_help[] = {
  "  -h, --help                Print help and exit",
  "      --full-help           Print help, including hidden options, and exit",
  "  -V, --version             Print version and exit",
  "\nUser creation options:",
  "  -t, --role=ENUM           User type  (possible values=\"admin\", \"normal\"\n                              default=`normal')",
  "  -a, --auth-file=STRING    Store authentication token in given file (instead\n                              of stdout)",
  "  -p, --pass-file=STRING    File containing user password (instead of stdin)",
  "  -d, --description=STRING  Set the description of this user  (default=`')",
  "  -q, --quota=SIZE          Set total quota for all volumes owned by this user\n                              (allows K,M,G,T suffixes)",
  "\nCommon options:",
  "  -c, --config-dir=PATH     Path to SX configuration directory",
  "      --force-key=TOKEN     Create user with an old authentication token",
  "  -g, --generate-key        Generate a random key  (default=off)",
  "  -b, --batch-mode          Disable additional information and only print the\n                              automatically generated key  (default=off)",
  "  -D, --debug               Enable debug messages  (default=off)",
    0
};

static void
init_help_array(void)
{
  useradd_args_info_help[0] = useradd_args_info_full_help[0];
  useradd_args_info_help[1] = useradd_args_info_full_help[1];
  useradd_args_info_help[2] = useradd_args_info_full_help[2];
  useradd_args_info_help[3] = useradd_args_info_full_help[3];
  useradd_args_info_help[4] = useradd_args_info_full_help[4];
  useradd_args_info_help[5] = useradd_args_info_full_help[5];
  useradd_args_info_help[6] = useradd_args_info_full_help[6];
  useradd_args_info_help[7] = useradd_args_info_full_help[7];
  useradd_args_info_help[8] = useradd_args_info_full_help[8];
  useradd_args_info_help[9] = useradd_args_info_full_help[9];
  useradd_args_info_help[10] = useradd_args_info_full_help[12];
  useradd_args_info_help[11] = useradd_args_info_full_help[13];
  useradd_args_info_help[12] = useradd_args_info_full_help[14];
  useradd_args_info_help[13] = 0; 
  
}

const char *useradd_args_info_help[14];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_ENUM
} useradd_cmdline_parser_arg_type;

static
void clear_given (struct useradd_args_info *args_info);
static
void clear_args (struct useradd_args_info *args_info);

static int
useradd_cmdline_parser_internal (int argc, char **argv, struct useradd_args_info *args_info,
                        struct useradd_cmdline_parser_params *params, const char *additional_error);


const char *useradd_cmdline_parser_role_values[] = {"admin", "normal", 0}; /*< Possible values for role. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct useradd_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->role_given = 0 ;
  args_info->auth_file_given = 0 ;
  args_info->pass_file_given = 0 ;
  args_info->description_given = 0 ;
  args_info->quota_given = 0 ;
  args_info->config_dir_given = 0 ;
  args_info->force_key_given = 0 ;
  args_info->generate_key_given = 0 ;
  args_info->batch_mode_given = 0 ;
  args_info->debug_given = 0 ;
}

static
void clear_args (struct useradd_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->role_arg = role_arg_normal;
  args_info->role_orig = NULL;
  args_info->auth_file_arg = NULL;
  args_info->auth_file_orig = NULL;
  args_info->pass_file_arg = NULL;
  args_info->pass_file_orig = NULL;
  args_info->description_arg = gengetopt_strdup ("");
  args_info->description_orig = NULL;
  args_info->quota_arg = NULL;
  args_info->quota_orig = NULL;
  args_info->config_dir_arg = NULL;
  args_info->config_dir_orig = NULL;
  args_info->force_key_arg = NULL;
  args_info->force_key_orig = NULL;
  args_info->generate_key_flag = 0;
  args_info->batch_mode_flag = 0;
  args_info->debug_flag = 0;
  
}

static
void init_args_info(struct useradd_args_info *args_info)
{

  init_help_array(); 
  args_info->help_help = useradd_args_info_full_help[0] ;
  args_info->full_help_help = useradd_args_info_full_help[1] ;
  args_info->version_help = useradd_args_info_full_help[2] ;
  args_info->role_help = useradd_args_info_full_help[4] ;
  args_info->auth_file_help = useradd_args_info_full_help[5] ;
  args_info->pass_file_help = useradd_args_info_full_help[6] ;
  args_info->description_help = useradd_args_info_full_help[7] ;
  args_info->quota_help = useradd_args_info_full_help[8] ;
  args_info->config_dir_help = useradd_args_info_full_help[10] ;
  args_info->force_key_help = useradd_args_info_full_help[11] ;
  args_info->generate_key_help = useradd_args_info_full_help[12] ;
  args_info->batch_mode_help = useradd_args_info_full_help[13] ;
  args_info->debug_help = useradd_args_info_full_help[14] ;
  
}

void
useradd_cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(USERADD_CMDLINE_PARSER_PACKAGE_NAME) ? USERADD_CMDLINE_PARSER_PACKAGE_NAME : USERADD_CMDLINE_PARSER_PACKAGE),
     USERADD_CMDLINE_PARSER_VERSION);

  if (strlen(useradd_args_info_versiontext) > 0)
    printf("\n%s\n", useradd_args_info_versiontext);
}

static void print_help_common(void) {
  useradd_cmdline_parser_print_version ();

  if (strlen(useradd_args_info_purpose) > 0)
    printf("\n%s\n", useradd_args_info_purpose);

  if (strlen(useradd_args_info_usage) > 0)
    printf("\n%s\n", useradd_args_info_usage);

  printf("\n");

  if (strlen(useradd_args_info_description) > 0)
    printf("%s\n\n", useradd_args_info_description);
}

void
useradd_cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (useradd_args_info_help[i])
    printf("%s\n", useradd_args_info_help[i++]);
}

void
useradd_cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (useradd_args_info_full_help[i])
    printf("%s\n", useradd_args_info_full_help[i++]);
}

void
useradd_cmdline_parser_init (struct useradd_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
useradd_cmdline_parser_params_init(struct useradd_cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct useradd_cmdline_parser_params *
useradd_cmdline_parser_params_create(void)
{
  struct useradd_cmdline_parser_params *params = 
    (struct useradd_cmdline_parser_params *)malloc(sizeof(struct useradd_cmdline_parser_params));
  useradd_cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
useradd_cmdline_parser_release (struct useradd_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->role_orig));
  free_string_field (&(args_info->auth_file_arg));
  free_string_field (&(args_info->auth_file_orig));
  free_string_field (&(args_info->pass_file_arg));
  free_string_field (&(args_info->pass_file_orig));
  free_string_field (&(args_info->description_arg));
  free_string_field (&(args_info->description_orig));
  free_string_field (&(args_info->quota_arg));
  free_string_field (&(args_info->quota_orig));
  free_string_field (&(args_info->config_dir_arg));
  free_string_field (&(args_info->config_dir_orig));
  free_string_field (&(args_info->force_key_arg));
  free_string_field (&(args_info->force_key_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
useradd_cmdline_parser_dump(FILE *outfile, struct useradd_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", USERADD_CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->role_given)
    write_into_file(outfile, "role", args_info->role_orig, useradd_cmdline_parser_role_values);
  if (args_info->auth_file_given)
    write_into_file(outfile, "auth-file", args_info->auth_file_orig, 0);
  if (args_info->pass_file_given)
    write_into_file(outfile, "pass-file", args_info->pass_file_orig, 0);
  if (args_info->description_given)
    write_into_file(outfile, "description", args_info->description_orig, 0);
  if (args_info->quota_given)
    write_into_file(outfile, "quota", args_info->quota_orig, 0);
  if (args_info->config_dir_given)
    write_into_file(outfile, "config-dir", args_info->config_dir_orig, 0);
  if (args_info->force_key_given)
    write_into_file(outfile, "force-key", args_info->force_key_orig, 0);
  if (args_info->generate_key_given)
    write_into_file(outfile, "generate-key", 0, 0 );
  if (args_info->batch_mode_given)
    write_into_file(outfile, "batch-mode", 0, 0 );
  if (args_info->debug_given)
    write_into_file(outfile, "debug", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
useradd_cmdline_parser_file_save(const char *filename, struct useradd_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", USERADD_CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = useradd_cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
useradd_cmdline_parser_free (struct useradd_args_info *args_info)
{
  useradd_cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
useradd_cmdline_parser (int argc, char **argv, struct useradd_args_info *args_info)
{
  return useradd_cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
useradd_cmdline_parser_ext (int argc, char **argv, struct useradd_args_info *args_info,
                   struct useradd_cmdline_parser_params *params)
{
  int result;
  result = useradd_cmdline_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
useradd_cmdline_parser2 (int argc, char **argv, struct useradd_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct useradd_cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = useradd_cmdline_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
useradd_cmdline_parser_required (struct useradd_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see useradd_cmdline_parser_params.check_ambiguity
 * @param override @see useradd_cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               useradd_cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
useradd_cmdline_parser_internal (
  int argc, char **argv, struct useradd_args_info *args_info,
                        struct useradd_cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct useradd_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    useradd_cmdline_parser_init (args_info);

  useradd_cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "role",	1, NULL, 't' },
        { "auth-file",	1, NULL, 'a' },
        { "pass-file",	1, NULL, 'p' },
        { "description",	1, NULL, 'd' },
        { "quota",	1, NULL, 'q' },
        { "config-dir",	1, NULL, 'c' },
        { "force-key",	1, NULL, 0 },
        { "generate-key",	0, NULL, 'g' },
        { "batch-mode",	0, NULL, 'b' },
        { "debug",	0, NULL, 'D' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVt:a:p:d:q:c:gbD", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          useradd_cmdline_parser_print_help ();
          useradd_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->version_given),
              &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "version", 'V',
              additional_error))
            goto failure;
          useradd_cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 't':	/* User type.  */
        
        
          if (update_arg( (void *)&(args_info->role_arg), 
               &(args_info->role_orig), &(args_info->role_given),
              &(local_args_info.role_given), optarg, useradd_cmdline_parser_role_values, "normal", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "role", 't',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Store authentication token in given file (instead of stdout).  */
        
        
          if (update_arg( (void *)&(args_info->auth_file_arg), 
               &(args_info->auth_file_orig), &(args_info->auth_file_given),
              &(local_args_info.auth_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "auth-file", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* File containing user password (instead of stdin).  */
        
        
          if (update_arg( (void *)&(args_info->pass_file_arg), 
               &(args_info->pass_file_orig), &(args_info->pass_file_given),
              &(local_args_info.pass_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "pass-file", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Set the description of this user.  */
        
        
          if (update_arg( (void *)&(args_info->description_arg), 
               &(args_info->description_orig), &(args_info->description_given),
              &(local_args_info.description_given), optarg, 0, "", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "description", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Set total quota for all volumes owned by this user (allows K,M,G,T suffixes).  */
        
        
          if (update_arg( (void *)&(args_info->quota_arg), 
               &(args_info->quota_orig), &(args_info->quota_given),
              &(local_args_info.quota_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "quota", 'q',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Path to SX configuration directory.  */
        
        
          if (update_arg( (void *)&(args_info->config_dir_arg), 
               &(args_info->config_dir_orig), &(args_info->config_dir_given),
              &(local_args_info.config_dir_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "config-dir", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Generate a random key.  */
        
        
          if (update_arg((void *)&(args_info->generate_key_flag), 0, &(args_info->generate_key_given),
              &(local_args_info.generate_key_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "generate-key", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Disable additional information and only print the automatically generated key.  */
        
        
          if (update_arg((void *)&(args_info->batch_mode_flag), 0, &(args_info->batch_mode_given),
              &(local_args_info.batch_mode_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "batch-mode", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* Enable debug messages.  */
        
        
          if (update_arg((void *)&(args_info->debug_flag), 0, &(args_info->debug_given),
              &(local_args_info.debug_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "debug", 'D',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            useradd_cmdline_parser_print_full_help ();
            useradd_cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Create user with an old authentication token.  */
          if (strcmp (long_options[option_index].name, "force-key") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->force_key_arg), 
                 &(args_info->force_key_orig), &(args_info->force_key_given),
                &(local_args_info.force_key_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "force-key", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", USERADD_CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  useradd_cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  useradd_cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
